### ISSUE TITLE
列表加载有的时候数据有问题

### ISSUE THREAD

**Issue by TakWolf** [shinygang/Vue-cnodejs#1]
![image](https://cloud.githubusercontent.com/assets/6064962/11453068/fd18126e-9637-11e5-92f9-89b5f2ca9847.png)
这是顶部

![image](https://cloud.githubusercontent.com/assets/6064962/11453073/13f1dc90-9638-11e5-9caa-79f59cadcb99.png)

这是中间

**Comment by shinygang** [comment]
@TakWolf 请我你说的是数据排序的问题还是距离顶部的样式问题？
如果是排序问题的话，是由于我们没有及时刷新数据引起的。

**Comment by Yunkou** [comment]
想到了，没有处理数据更新处理

**Comment by Yunkou** [comment]
@TakWolf   @shinygang  cnode api 支持的有限，就目前的API来看应该是解决不了这个问题，我到安卓客户端去求教下看那边怎么处理的

**Comment by Yunkou** [comment]
@TakWolf  我刚看到，你开发了安卓版本，求教你是怎么处理的。

**Comment by TakWolf** [comment]
@shinygang @Yunkou 

是数据加载重复了，分页的第一页加载了两次

感觉是分页参数的问题，你检查一下

**Comment by shinygang** [comment]
@TakWolf 是由于有最新评论，把之前数据顶下去了，所以加载第二页就重复了，我们展示数据是累加的。

**Comment by TakWolf** [comment]
@shinygang 

没太明白。意思是有新的回复的时候，恰好加载第二页，由于列表数据变化了，可能会出现重复的item吗？

刚才看了一下，这个问题还是存在的，看第二张截图，有一个置顶帖子。从置顶向下一部分都是重复的。

置顶帖出现在中间部分感觉是不太合理的

**Comment by TakWolf** [comment]
数了一下，分页page = 20，正好是第一页加载了两次

**Comment by TakWolf** [comment]
![image](https://cloud.githubusercontent.com/assets/6064962/11466340/356b3fda-977b-11e5-8c9f-9bb069b6e075.png)

![image](https://cloud.githubusercontent.com/assets/6064962/11466342/3a691cf0-977b-11e5-81c4-6b78e771c0cc.png)

是不是这里的问题。分页是从1开始计算的。

**Comment by shinygang** [comment]
@TakWolf 哦哦，谢谢你的提醒，我现在感觉有个问题就是，如果用户在第一页停留时，这个时候有主题被回复了，下拉加载第二页的话，数据会重复。

**Comment by TakWolf** [comment]
@shinygang 

这个问题没解。
有一个方案是 api 这块改成通过topicId来进行分页：  after={topicId} , before={topicId}

我感觉这个问题不用处理就好啦，不会产生太大的问题，即便会出现个别重复的item

**Comment by shinygang** [comment]
@TakWolf 恩恩，我现在是这样搞的，第一页请求0-20条，第二页请求的0-40条... 然后替换页面的数据源。哈哈，一般用户也不回下拉太长。

**Comment by TakWolf** [comment]
“第二页请求的0-40条”

这样搞不会有问题吗....感觉不太妙啊

**Comment by shinygang** [comment]
我的想法是第二页包含覆盖第一页的数据，相当于分页的操作，哈哈，也是临时救急，没找到解决上面那个问题的方案。

**Comment by Yunkou** [comment]
@TakWolf 我在sf上提问   http://segmentfault.com/q/1010000004069063 是最佳的但是 cnode 没有提供这样的API。 如回答，更新方式类似朋友圈的更新方式。
