### ISSUE TITLE
windows安装环境报错

### ISSUE THREAD

**Issue by mlyknown** [shinygang/Vue-cnodejs#21]
node-sass 模块报错，好像和系统有关系，查了资料，还是不知怎么解决 0.0

js
   [0] multi main 28 bytes {0} [built]
       factory:0ms building:10ms = 10ms
    + 114 hidden modules

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-98ff9be0&file=index.vue!./~/sass-loader!./~/vue-loader/lib/selector.js?t
ype=style&index=0!./src/views/index.vue 4:14-282

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-e1dbd576&file=message.vue!./~/sass-loader!./~/vue-loader/lib/selector.js
?type=style&index=0!./src/views/message.vue 4:14-286

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-236d6544&file=new.vue!./~/sass-loader!./~/vue-loader/lib/selector.js?typ
e=style&index=0!./src/views/new.vue 4:14-278

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-7d27d527&file=login.vue!./~/sass-loader!./~/vue-loader/lib/selector.js?t
ype=style&index=0!./src/views/login.vue 4:14-282

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-7b86247d&file=user.vue!./~/sass-loader!./~/vue-loader/lib/selector.js?ty
pe=style&index=0!./src/views/user.vue 4:14-280

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-029e97bf&file=header.vue!./~/sass-loader!./~/vue-loader/lib/selector.js?
type=style&index=0!./src/components/header.vue 4:14-284

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-7cb3599c&file=nvAlert.vue!./~/sass-loader!./~/vue-loader/lib/selector.js
?type=style&index=0!./src/components/nvAlert.vue 4:14-286

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-0124b00c&file=loading.vue!./~/sass-loader!./~/vue-loader/lib/selector.js
?type=style&index=0!./src/components/loading.vue 4:14-286

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-c7aedfde&file=menu.vue!./~/sass-loader!./~/vue-loader/lib/selector.js?ty
pe=style&index=0!./src/components/menu.vue 4:14-280

ERROR in %1 is not a valid Win32 application.
\?\D:\MyProject\git-demo\Vue-cnodejs\node_modules\node-sass\vendor\win32-x64-46
\binding.node
 @ ./~/style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.j
s?id=_v-1584dcae&file=user-info.vue!./~/sass-loader!./~/vue-loader/lib/selector.
js?type=style&index=0!./src/components/user-info.vue 4:14-290
Child extract-text-webpack-plugin:

**Comment by shinygang** [comment]
你用国内的cnpm安装呢？多装几次吧。

**Comment by Loyalsoldier** [comment]
最近 node-sass 好像兼容性有问题。我在墙外的 Linux 系统上安装也会出问题。

建议这样：

```
npm install nrm -g  // 全局安装 nrm 这个插件
nrm use taobao  // 切换 npm 源为淘宝的镜像
npm config set proxy= // 去掉 npm 的代理设置
npm uninstall --save-dev node-sass
npm cache clean
npm install --save-dev node-sass
```

**Comment by Loyalsoldier** [comment]
@shinygang 建议以后发 node 的项目，使用 `npm shrinkwrap` 命名

**Comment by mlyknown** [comment]
thanks。。使用cnpm就ok了
