### ISSUE TITLE
依赖包有问题

### ISSUE THREAD

**Issue by maochunguang** [shinygang/Vue-cnodejs#23]
npm install之后启动不行，提示source-map没有，安装完source-map，提示soure-list，

**Comment by shinygang** [comment]
@maochunguang 请问什么环境？我晚上回家试一试。

**Comment by maochunguang** [comment]
我是在win10和mac上都试了,node版本0.12.9,npm install安装完依赖,启动就不行了

13240105904@163.com

发件人： TG
发送时间： 2016-03-07 13:43
收件人： shinygang/Vue-cnodejs
抄送： tommy
主题： Re: [Vue-cnodejs] 依赖包有问题 (#23)
@maochunguang 请问什么环境？我晚上回家试一试。

**Comment by shinygang** [comment]
先升级你的node版本啊，我们用v4.*

**Comment by maochunguang** [comment]
谢谢啊,我在试一下,

13240105904@163.com

发件人： 13240105904@163.com
发送时间： 2016-03-07 13:57
收件人： shinygang/Vue-cnodejs
主题： Re: Re: [Vue-cnodejs] 依赖包有问题 (#23)
我是在win10和mac上都试了,node版本0.12.9,npm install安装完依赖,启动就不行了

13240105904@163.com

发件人： TG
发送时间： 2016-03-07 13:43
收件人： shinygang/Vue-cnodejs
抄送： tommy
主题： Re: [Vue-cnodejs] 依赖包有问题 (#23)
@maochunguang 请问什么环境？我晚上回家试一试。
