### ISSUE TITLE
启动 node server.js 的时候遇到这样的问题

### ISSUE THREAD

**Issue by yaonie084** [shinygang/Vue-cnodejs#26]
ERROR in ./src/main.js
Module build failed: ReferenceError: [BABEL] /Users/ethan/node/Vue-cnodejs/src/main.js: Using removed Babel 5 option: /Users/ethan/node/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets

**Comment by shinygang** [comment]
你安装babel了吗？

**Comment by yaonie084** [comment]
需要全局安装吗？

**Comment by yaonie084** [comment]
没有单独去装babel，只在目录里运行了一下npm install

**Comment by shinygang** [comment]
不需要 ，你看你模块安装目录有babel相关的文件吗？

**Comment by yaonie084** [comment]
里面什么都没有动过。这里是哪个模块在起作用呢？

**Comment by shinygang** [comment]
你qq多少？你加我qq 429517385,我看看你的安装。

**Comment by yaonie084** [comment]
加了。
