### ISSUE TITLE
安卓微信端view无法跳转

### ISSUE THREAD

**Issue by welchwsy** [shinygang/Vue-cnodejs#30]
访问的是这个地址[http://www.shinygang.cn/cnodevue/#!/list](http://www.shinygang.cn/cnodevue/#!/list)

在ios的微信端打开正常，android中的uc浏览器也是正常的。测试小米3（miui7）/ ZTE星星2号（android4.4）的微信端无法进入贴子的详情页，登陆界面也是无法打开的。

chrome调试可以看到以下的警告信息：

```
[Vue warn]: Attribute "v-transition" is ignored on component <router-view> because the component is a fragment instance: http://vuejs.org/guide/components.html#Fragment_Instance
```

**Comment by shinygang** [comment]
可以跳转啊，试了，正常的啊。是不是你网络问题。警告这个不影响
