### ISSUE TITLE
关于sass的一些问题。

### ISSUE THREAD

**Issue by palmerye** [shinygang/Vue-cnodejs#31]
Vue组件里用sass写样式，外联sass样式在webpack.config里配置loader没问题的。

但在内联写sass就不行，需要在其他地方有什么配置么?

<style lang="sass">..</style>

问题：编译报错，内联无法渲染样式，

**Comment by palmerye** [comment]
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader?indentedSyntax!./~/vue-loader/lib/selector.js?type=style&index=0!./src/views/home.vue
Module build failed:
        <slider :banner="banner"></slider>
           ^
      Invalid CSS after ".container {": expected "}", was "{"
      in /Users/yangmingming/LiaoXinWang/LiaoXinWang-WeChat/src/views/home.vue (line 3, column 13)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader?indentedSyntax!./~/vue-loader/lib/selector.js?type=style&index=0!./src/views/home.vue 4:14-256 13:2-17:4 14:20-262

**Comment by shinygang** [comment]
内联在style 标签后面加 lang="sass"
