### ISSUE TITLE
怎么在vue里使用jQuery选择器

### ISSUE THREAD

**Issue by zq741235** [shinygang/Vue-cnodejs#34]
你好我看到你的项目里面有用到jQuery选择器，我想请问是要引入些什么还是怎么做？

**Comment by shinygang** [comment]
我们项目里面其实已经引用了zepto的东西，你页面直接用就可以了，webpack里面已经配置了$的选择器。

**Comment by Yunkou** [comment]
不过还是建议，少用jquery和zepto。
