### ISSUE TITLE
npm run dist  时候报错

### ISSUE THREAD

**Issue by dragonsayok** [shinygang/Vue-cnodejs#37]
verbose pkgid Vue-Cnodejs@1.0.0
16 verbose cwd C:\lab\cnnode\Vue-cnodejs
17 error Windows_NT 6.1.7601
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Users\zhanghao\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\bin\npm-cli.js" "--userconfig=C:\Users\zhanghao\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "dist"
19 error node v6.2.0
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error Vue-Cnodejs@1.0.0 dist: `NODE_ENV=development gulp`
22 error Exit status 1
23 error Failed at the Vue-Cnodejs@1.0.0 dist script 'NODE_ENV=development gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Vue-Cnodejs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=development gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Vue-Cnodejs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Vue-Cnodejs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by shinygang** [comment]
Windows 的环境要这样处理：

```
set NODE_ENV=development
gulp
```
