### ISSUE TITLE
运行不起来。。。。

### ISSUE THREAD

**Issue by baruide** [shinygang/Vue-cnodejs#38]
该怎么运行起来啊

**Comment by shinygang** [comment]
把你的运行环境和报错截图弄说一下。

**Comment by lookST** [comment]
ubuntu系统, node v4.4.5,
`npm install`安装和`node server.js`启动服务没报错，chrome访问`http://localhost:8090`时报错如下：
![image](https://cloud.githubusercontent.com/assets/11820152/16215145/feaa1932-3791-11e6-9d0b-ef215d1e21d2.png)
