### ISSUE TITLE
执行npm i时报错

### ISSUE THREAD

**Issue by Anshiii** [shinygang/Vue-cnodejs#39]
D:\Home\Vue-cnodejs>npm i
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN deprecated cssnext-loader@1.0.1: cssnext is now postcss-cssnext. cssnex
t-loader is deprecated. Use postcss-loader. See postcss-cssnext migration guide
http://cssnext.io/postcss/
npm WARN deprecated cssnext@1.8.4: cssnext is now postcss-cssnext. cssnext is de
precated. See postcss-cssnext migration guide http://cssnext.io/postcss/
npm WARN deprecated css-list@0.1.3: Deprecated.
npm WARN deprecated lodash@2.4.0: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade
 to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a bu
ild toolchain, use it instead!
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  nextstepwebs/codemirror-spell-checker resetting remote C:
\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-github-com-nextstepwebs-
codemirror-spell-checker-git-9a7087ad because of error: { Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT'
}
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  codemirror/CodeMirror resetting remote C:\Users\Anshi\App
Data\Roaming\npm-cache_git-remotes\git-github-com-codemirror-CodeMirror-git-6d6
d6466 because of error: { Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT'
}
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git://github.com/codemirror/CodeMirror.git C:\Users\Ansh
i\AppData\Roaming\npm-cache_git-remotes\git-github-com-codemirror-CodeMirror-gi
t-6d6d6466: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git://github.com/codemirror/CodeMirror.git C:\Users\Ansh
i\AppData\Roaming\npm-cache_git-remotes\git-github-com-codemirror-CodeMirror-gi
t-6d6d6466: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git://github.com/nextstepwebs/codemirror-spell-checker.g
it C:\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-github-com-nextstep
webs-codemirror-spell-checker-git-9a7087ad: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git://github.com/nextstepwebs/codemirror-spell-checker.g
it C:\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-github-com-nextstep
webs-codemirror-spell-checker-git-9a7087ad: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  nextstepwebs/codemirror-spell-checker resetting remote C:
\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-nextste
pwebs-codemirror-spell-checker-git-47b91323 because of error: { Error: not found
: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT'
}
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  codemirror/CodeMirror resetting remote C:\Users\Anshi\App
Data\Roaming\npm-cache_git-remotes\git-https-github-com-codemirror-CodeMirror-g
it-98d47346 because of error: { Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT'
}
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror https://github.com/nextstepwebs/codemirror-spell-checker
.git C:\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-
nextstepwebs-codemirror-spell-checker-git-47b91323: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror https://github.com/nextstepwebs/codemirror-spell-checker
.git C:\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-
nextstepwebs-codemirror-spell-checker-git-47b91323: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror https://github.com/codemirror/CodeMirror.git C:\Users\An
shi\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-codemirror-CodeM
irror-git-98d47346: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror https://github.com/codemirror/CodeMirror.git C:\Users\An
shi\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-codemirror-CodeM
irror-git-98d47346: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  nextstepwebs/codemirror-spell-checker resetting remote C:
\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-github-com-nextstepwebs-
codemirror-spell-checker-git-28ea4882 because of error: { Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT'
}
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  codemirror/CodeMirror resetting remote C:\Users\Anshi\App
Data\Roaming\npm-cache_git-remotes\git-github-com-codemirror-CodeMirror-git-6f6
044cc because of error: { Error: not found: git
npm WARN addRemoteGit     at F (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:63:19)
npm WARN addRemoteGit     at E (D:\Nodejs\node_modules\npm\node_modules\which\wh
ich.js:72:29)
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\which
.js:81:16
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\Nodejs\node_modules\npm\node_modules\which\node_
modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT'
}
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git@github.com:codemirror/CodeMirror.git C:\Users\Anshi\
AppData\Roaming\npm-cache_git-remotes\git-github-com-codemirror-CodeMirror-git-
6f6044cc: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git@github.com:codemirror/CodeMirror.git C:\Users\Anshi\
AppData\Roaming\npm-cache_git-remotes\git-github-com-codemirror-CodeMirror-git-
6f6044cc: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git@github.com:nextstepwebs/codemirror-spell-checker.git
 C:\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-github-com-nextstepwe
bs-codemirror-spell-checker-git-28ea4882: undefined
npm ERR! git clone --template=C:\Users\Anshi\AppData\Roaming\npm-cache_git-remo
tes_templates --mirror git@github.com:nextstepwebs/codemirror-spell-checker.git
 C:\Users\Anshi\AppData\Roaming\npm-cache_git-remotes\git-github-com-nextstepwe
bs-codemirror-spell-checker-git-28ea4882: undefined
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.12
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "D:\Nodejs\node.exe" "D:\Nodejs\node_modules\npm\bin\npm-cl
i.js" "i"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Home\Vue-cnodejs\npm-debug.log
等。。。

**Comment by shinygang** [comment]
请问你是node哪个版本，我当时用的V4.*

**Comment by Anshiii** [comment]
6.1.0

**Comment by shinygang** [comment]
@Anshiii 你肯定还是模块没安装好，再重新安装下吧。

**Comment by liujie3612** [comment]
建议先连上vpn在 npm install

**Comment by liujie3612** [comment]
建议先连上vpn 再执行npm install
