### ISSUE TITLE
安卓侧边栏

### ISSUE THREAD

**Issue by hhythink** [shinygang/Vue-cnodejs#44]
安卓里面侧边栏链接点不了

**Comment by shinygang** [comment]
@hhythink 
什么浏览器？

**Comment by hhythink** [comment]
我我直接在微信里面打开的

**Comment by shinygang** [comment]
@hhythink 你登录了吗？我刚才试了，可以点击啊。

**Comment by hhythink** [comment]
没登录，这个也得给个提示啊，再一个我点侧边栏的关于也没反应，这个也跟登录有关系吗?

**Comment by shinygang** [comment]
@hhythink 没登录你点击会跳转登录界面啊。

**Comment by hhythink** [comment]
没有跳转，感觉像是卡机了，我直接把微信关了，才能打开别的，我的机子是华为荣耀plus

**Comment by shinygang** [comment]
@hhythink 你用其他浏览器试一试。

**Comment by hhythink** [comment]
刚试了其它浏览器可以，微信不行

**Comment by shinygang** [comment]
没有你那种机子，没法调了。你自己调调吧。
