### ISSUE TITLE
关于如何监测localStorage

### ISSUE THREAD

**Issue by pramper** [shinygang/Vue-cnodejs#48]
你好，我想知道你是如何监测localStorage的变化的。你在login组件中给localStorage赋值后，在user-info直接使用下面的形式监听localStorage的变化：

``` javascript
data() {
  loginname: localStorage.loginname || ''
}
```

我试了试，折腾了一晚上，最终发现localStorage的变化vue是无法监测的。我看了很多遍你的源码，仍然没发现你是怎么实现的，能不能解答一下？谢谢了。

**Comment by shinygang** [comment]
@pramper 你为什么要监听localStorage呢？我在登录页面存的用户信息，然后页面跳转vue-router的data里面去获取用户登录名啊。

**Comment by sinian1989** [comment]
你好 你那个点击跳转页面时候有个等待的转圈的图 那图是GIF吗 还是个组件？怎么写 才会有跳转等待？

**Comment by sinian1989** [comment]
可不可以加下你QQ 我的282787275

**Comment by shinygang** [comment]
@sinian1989 那个是gif，写在body里面的背景图。加我QQ吧：429517385
