### ISSUE TITLE
我克隆本地爆sass错误

### ISSUE THREAD

**Issue by musclejack** [shinygang/Vue-cnodejs#54]
我克隆本地爆sass错误；
ERROR in ENOENT: no such file or directory, scandir 'C:\Users\Mz\Desktop\gitconde\Vue-cnode
js\node_modules.3.10.0@node-sass\vendor'
 @ ./~/.0.13.1@style-loader!./~/.0.23.1@css-loader?sourceMap!./~/.7.5.3@vue-loader/lib/styl
e-rewriter.js?id=_v-65e4ff2e&file=user-info.vue!./~/.3.2.3@sass-loader!./~/.7.5.3@vue-loade
r/lib/selector.js?type=style&index=0!./src/components/user-info.vue 4:14-319 13:2-17:4 14:2
0-325
Child extract-text-webpack-plugin:

```
ERROR in ENOENT: no such file or directory, scandir 'C:\Users\Mz\Desktop\gitconde\Vue-c
```

nodejs\node_modules.3.10.0@node-sass\vendor'

依赖安装了的，就是报这个错误，然后我发现真的没有C:\Users\Mz\Desktop\gitconde\Vue-c
nodejs\node_modules.3.10.0@node-sass\vendor这个文件夹，怎么样才可以本地安装成功呢

**Comment by shinygang** [comment]
sass-loader 没装好，不要通过cnpm装，要用npm装。

**Comment by musclejack** [comment]
谢谢，搞定了
