### ISSUE TITLE
在微信中浏览demo，点击菜单栏，程序卡死

### ISSUE THREAD

**Issue by smilease** [shinygang/Vue-cnodejs#55]

**Comment by shinygang** [comment]
@smilease 没有发现你说的问题，这个和程序关系不大

**Comment by smilease** [comment]
又测试过，点文章也点不开，浏览器访问正常，微信访问不行。如果你的作品也希望用在微信上，可能还需要做适配上的测试和调整

**Comment by smilease** [comment]
http://www.shinygang.cn/cnodevue/#!/list
我是通过把上面的链接分享到微信，在微信里点开访问的。 微信版本6.3.27 手机系统android 6.0 机型 华为mate7

**Comment by shinygang** [comment]
@smilease 我也是用的安卓6.3.27，我是小米的机子，刚才试了，访问正常。个人项目可能没那么多的经历去做机型适配了，抱歉。

**Comment by smilease** [comment]
不用抱歉，非常感谢您提供的作品
