### ISSUE TITLE
运行npm install报错

### ISSUE THREAD

**Issue by lxz612** [shinygang/Vue-cnodejs#57]
运行了好几遍后，还是有以下错误。项目能跑起来，但浏览器访问是空白一片。我的是window环境，请问该怎么解决？
好像学习下，然后自己写一个出来...

npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (D:\nodejs\node_modules\npm\node_modules\which\which.js:63:19)
npm WARN addRemoteGit     at E (D:\nodejs\node_modules\npm\node_modules\which\which.js:72:29)
npm WARN addRemoteGit     at D:\nodejs\node_modules\npm\node_modules\which\which.js:81:16
npm WARN addRemoteGit     at D:\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN addRemoteGit  git+http://ikt.pm2.io/ikt.git#master resetting remote C:\Users\612\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2 because of error: { Error: not found: git
npm WARN addRemoteGit     at F (D:\nodejs\node_modules\npm\node_modules\which\which.js:63:19)
npm WARN addRemoteGit     at E (D:\nodejs\node_modules\npm\node_modules\which\which.js:72:29)
npm WARN addRemoteGit     at D:\nodejs\node_modules\npm\node_modules\which\which.js:81:16
npm WARN addRemoteGit     at D:\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at D:\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\612\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://ikt.pm2.io/ikt.git C:\Users\612\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2: undefined
npm ERR! git clone --template=C:\Users\612\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://ikt.pm2.io/ikt.git C:\Users\612\AppData\Roaming\npm-cache\_git-remotes\git-http-ikt-pm2-io-ikt-git-master-d352a2a2: undefined
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /pm2/ikt:
npm WARN not found: git
npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

**Comment by shinygang** [comment]
@lxz612 你的报错信息提示的没有找到git啊，你需要先安装git。
