### ISSUE TITLE
可以增加一个使用 vue-cli 构建的分支吗？

### ISSUE THREAD

**Issue by yisibl** [shinygang/Vue-cnodejs#58]
官方的 Webpack 模板是：https://github.com/vuejs-templates/webpack
master 分支我直接替换为这个编译，list 页面 CSS 刷新后失效。

**Comment by shinygang** [comment]
可以的，我抽空弄一版这个分支出来。

**Comment by yisibl** [comment]
@shinygang 我感觉把所有 views 里的 CSS 都用 `<style src="" lang="scss">`的方式引入比较好。

**Comment by shinygang** [comment]
@yisibl 这个其实看个人吧，我现在开发项目也喜欢这样弄。这个开源项目先不这样改了。

**Comment by shinygang** [comment]
@yisibl 更新master分支用vue-cli构建。

**Comment by yisibl** [comment]
@shinygang 不错不错，不过非首页刷新后样式会丢失，我本地已经把所有 CSS 改为外联的方式了。

**Comment by yisibl** [comment]
另外之前版本的这个配置是否要加回去？

https://github.com/shinygang/Vue-cnodejs/blob/not_vue_cli/webpack.config.js#L20-L23

**Comment by shinygang** [comment]
@yisibl 由于使用了eslint，页面上调用的元素都必须要声明，我没想到好的方式处理这个问题。

**Comment by yisibl** [comment]
应该是添加这个就可以了：

``` json
"env": {
    "jquery": true
  }
```
