### ISSUE TITLE
不能记住滚动位置，导致首页翻了的帖子点进去看，但是回到首页又到顶部了，有要翻翻翻找到我要看的下一个帖子

### ISSUE THREAD

**Issue by IndexXuan** [shinygang/Vue-cnodejs#6]
希望提供个改进，这个很影响体验！顺便想偷窥下vue router怎么做到这个，😄

**Comment by shinygang** [comment]
vue-router 有个saveScrollPosition属性，但是要只在 HTML5 history 模式下可用，由于用的github pages做的静态资源服务器，用html5 history会导致子页面刷新404，没法自定义nginx rewrites.所以暂时没法支持。
详情见[官方文档](http://vuejs.github.io/vue-router/zh-cn/options.html).

**Comment by IndexXuan** [comment]
@shinygang  可是太影响体验了，对于app来说是个致命问题。要不在框架给的生命周期里手动记录滚动位置，然后维护这个状态对象。😄 key：pageid，value：scrolltop。

**Comment by shinygang** [comment]
@IndexXuan 恩恩，也只能这样了，完善更新你说的，谢谢提建议。

**Comment by IndexXuan** [comment]
@shinygang  兄台客气，期待新特性！还有有时候后退貌似数据重刷了，首页只有header bar，没数据，大概十次有三次，持续0.几秒，你看看。不知道你的数据是缓存的还是每次进视图都fetch。建议能缓存的全缓存，嘿嘿！

**Comment by shinygang** [comment]
@IndexXuan 哥们，处理掉了。你看看。

**Comment by IndexXuan** [comment]
不错，去看代码去😄
