### ISSUE TITLE
增加页面加载进度条

### ISSUE THREAD

**Issue by yisibl** [shinygang/Vue-cnodejs#60]
例如这个 https://github.com/BosNaufal/vue2-loading-bar ？

**Comment by shinygang** [comment]
页面默认加了loding效果图片的，加这个意义不是很大，而且每个页面要去控制他的加载进度和加载完成状态。  @yisibl 你可以在你那边尝试。

**Comment by yisibl** [comment]
所以现在的 loading 效果和加到 `router.beforeEach` 和 `router.afterEach` 中的类似？

**Comment by shinygang** [comment]
@yisibl 不一样的，页面的loading有一定数据加载的效果，路由的钩子是页面切换。

**Comment by yisibl** [comment]
好的谢谢解答

**Comment by BarryZhan** [comment]
@yisibl 加载进度数值要怎么样实现呢？
