### ISSUE TITLE
topic 详情页 回复其他人后 reply组件不消失

### ISSUE THREAD

**Issue by wxh2013** [shinygang/Vue-cnodejs#65]
## topic 详情页 回复其他人后 reply组件不消失

![screen shot 2016-11-11 at 10 39 59 am](https://cloud.githubusercontent.com/assets/7362131/20202599/4cab370e-a7fb-11e6-87f1-0f1fb25aaaf0.png)

## 另外， 进入 topic 详情页后 再次刷新会出现异常

![screen shot 2016-11-11 at 10 41 30 am](https://cloud.githubusercontent.com/assets/7362131/20202632/89b3641e-a7fb-11e6-9529-d22b505af2bd.png)

**Comment by shinygang** [comment]
最新代码处理了，最近太忙了，一直没时间弄。
