### ISSUE TITLE
user 界面最新回复列表 点击他人头像不能跳转

### ISSUE THREAD

**Issue by wxh2013** [shinygang/Vue-cnodejs#66]
##   版本是最新的 master 分支

![screen shot 2016-11-11 at 5 15 26 pm](https://cloud.githubusercontent.com/assets/7362131/20210079/afe26ce8-a832-11e6-8f63-475041d14b7b.png)

**Comment by shinygang** [comment]
最新代码处理了，最近太忙了，一直没时间弄。
