### ISSUE TITLE
增加文章收藏功能

### ISSUE THREAD

**Issue by nicyxiao** [shinygang/Vue-cnodejs#67]
我看 CNode 是有 `post /topic_collect/collect` 收藏主题的接口的，不知可否增加一个这个功能？

**Comment by cwsjoker** [comment]
我自己也写了一个，这个是有的https://github.com/cwsjoker/Cnode-vue-spa，可以参考下

**Comment by shinygang** [comment]
@nicyxiao 暂时没想好放什么位置。页面很紧凑了，先不加了吧。
