### ISSUE TITLE
list.vue 代码优化

### ISSUE THREAD

**Issue by huaf22** [shinygang/Vue-cnodejs#68]
首先感谢开源了该项目, 可以让初学者学习项目结构和代码
![image](https://cloud.githubusercontent.com/assets/5006161/20614212/d4e92264-b306-11e6-9907-07f2830b3be4.png)

window.window.sessionStorage 方法在list.vue中很多地方都调用了, 可以定义一个全局变量代替

**Comment by shinygang** [comment]
@huaf22 应该是window. sessionStorage,手误了，window. sessionStorage这个的话没必要单独提变量了。
