### ISSUE TITLE
打包后问题

### ISSUE THREAD

**Issue by wxh2013** [shinygang/Vue-cnodejs#69]
这是打包后服务器的样子，  没有样式。
![screen shot 2016-12-06 at 2 02 54 pm](https://cloud.githubusercontent.com/assets/7362131/20914807/f7589d7a-bbbc-11e6-922c-0cb70b342f70.png)

这是打包后本地打开，  先是可以看到启动页， 然后就跳到这页了。
![screen shot 2016-12-06 at 2 03 11 pm](https://cloud.githubusercontent.com/assets/7362131/20914840/1f444e7e-bbbd-11e6-9d2f-80eb97a21dbe.png)

webpack  +   打包  的问题， 说起来满满的眼泪啊，  自己的项目也在解决这问题。   望大神快点解决。。。。

**Comment by zannet** [comment]
同遇到这个问题，vue-cli 版 npm run build 后css文件样式缺失

**Comment by shinygang** [comment]
@wxh2013  @zannet  问题已经处理，请更新最新代码
