### ISSUE TITLE
有考虑过把 moment 去掉么？

### ISSUE THREAD

**Issue by tthallos** [shinygang/Vue-cnodejs#7]
去掉`moment`之后，`build.min.js`小了一半。

目前好像只用了`moment`的两个方法，完全可以自己写的。

**Comment by shinygang** [comment]
@mage3k 谢谢建议，我抽空去掉

**Comment by shinygang** [comment]
@mage3k 我看moment库不大啊。

**Comment by tthallos** [comment]
@shinygang 是吗，我看看是不是我改了其他地方。反正现在`build`之后文件比之前小了很多。整理好了我再提个`PR`

**Comment by shinygang** [comment]
@mage3k 好的。谢谢支持。我最近工作有点忙，还没来得及维护更新东西。

**Comment by shinygang** [comment]
@mage3k moment库加进去确实很大，看来还的去掉。

**Comment by shinygang** [comment]
@mage3k 你微信多少，加个微信
