### ISSUE TITLE
1.0的相关疑惑

### ISSUE THREAD

**Issue by TerrenceFong** [shinygang/Vue-cnodejs#70]
由于没时间看2.0的教程，所以先用1.0的版本练练手。
我运行之后会提示下方的错误，请问这个如何解决的，我找了半天没有看到用了directive的地方。
`[Vue warn]: Failed to resolve directive: class`

还有就是我没在项目里面找到<router-view></router-view>，请问是如何控制跳转的？是通过node来控制的吗？

**Comment by shinygang** [comment]
建议直接看2.0的。1.0迟早的淘汰。跳转采用的vue-router。

**Comment by TerrenceFong** [comment]
额... 打少了一句 我知道是用vue-router，那为啥不需要用<router-view></router-view>这个标签来控制的，主要是想问这个和directive报错= =
