### ISSUE TITLE
github pges 设置404方法

### ISSUE THREAD

**Issue by lzxb** [shinygang/Vue-cnodejs#71]
https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by lzxb** [comment]
看到你的页面刷新之后，就没有返回html入口文件。不知道你的是不是github pages上面部署的

**Comment by shinygang** [comment]
@lzxb 哈哈，谢谢提醒，我之前是用的history模式，这个需要单独配置东西，现在改成hash了。刷新没问题了。
