### ISSUE TITLE
1.0的list.vue有个小bug

### ISSUE THREAD

**Issue by TerrenceFong** [shinygang/Vue-cnodejs#73]
虽然1.0会逐渐被淘汰，秉承着学习的心疼先把1.0的给看一遍，发现list.vue里面有个小bug，不过不影响整体使用。
74行的`this.searchKey.limit = 20;`没有起到重置limit的效果，是因为下一行的`this.searchKey = JSON.parse(this.searchDataStr);`掩盖了这里。
74行直接修改的是`searchKey`，然而重置的时候是使用了`searchDataStr`。由于一开始定义的时候就设置好了`limit`，所以重置时使用的是初始化的limit。
不知道2.0的版本有没有相关的问题。

**Comment by shinygang** [comment]
@TerrenceFong 感谢你的关注，这代码没问题，this.searchKey.limit = 20 这句话其实重复了，searchDataStr这个字段就是存储默认上面定义的首次查询条件，类似初始化查询条件的效果。默认limit是20.
