### ISSUE TITLE
请问'webpack-zepto'能够解决跨域问题吗？

### ISSUE THREAD

**Issue by hezhongfeng** [shinygang/Vue-cnodejs#74]
我使用`axios`这个请求库
是访问不了cnode的，应该是跨域的问题
为什么'webpack-zepto'就可以

**Comment by shinygang** [comment]
cnode的接口是允许跨域请求的，axios我没使用过，不太清楚，你可以看看他的文档。

**Comment by hezhongfeng** [comment]
好的
谢谢
