### ISSUE TITLE
一直下拉刷新，感觉有点蛋疼。

### ISSUE THREAD

**Issue by LeslieYQ** [shinygang/Vue-cnodejs#8]
建议修改成下啦几屏，然后分页是不是更好点。同时你应该开一个 issue来讨论下一步计划。

**Comment by shinygang** [comment]
@LeslieYQ 现在手机端不适合做分页，比较流行的方案都是下拉刷新。这几天比较忙，没有更新代码了，后期准备代码升级es6,然后UI优化。希望可以一起参与进来。

**Comment by Yunkou** [comment]
@LeslieYQ  你有什么好的建议？

**Comment by LeslieYQ** [comment]
我觉得是这样的，个人一直不太喜欢下拉刷新一直刷，有时候寻找不好寻找，这真是一个问题，很多App的做法是这样子，感觉是因为他们的特性，但是对于论坛而言，是知识的获得地，真的需要一个很好的查找功能，要么能提供一个强大的查找，要么就能快速的翻阅。你们觉得？ ES6 应该早点切换，vue支持的很好。愿意加入进来。但是需要一个计划。要不没有头绪。

**Comment by shinygang** [comment]
@LeslieYQ 是这样的，cnodejs暴露的API就是一些简单的API，没法做查询。Es6我们会马上启动更新，这个确实很有必要，就是平时比较忙，有时候来不及顾及，一起参与进来吧。
