### ISSUE TITLE
正常安装依赖，npm run dev，webpack报错了，本地运行不起来

### ISSUE THREAD

**Issue by fhvknb** [shinygang/Vue-cnodejs#83]
ERROR in ./~/css-loader?{"minimize":false}!./~/vue-loader/lib/style-compiler?{"id":"data-v-e91ade38","scoped":false,"hasInlineConfig":false}!./~/sass-loader?{}!./~/vue-loader/lib/selector
.js?type=styles&index=0!./src/views/login.vue
    Module build failed: Error: Cannot find module 'node-sass'

**Comment by shinygang** [comment]
@RalphXiang 请安装node-sass模块

**Comment by fhvknb** [comment]
win7 64 node 6.9.5 npm 3.10  为什么node-sass 安装不成功呢

**Comment by shinygang** [comment]
自己根据报错信息去解决吧。window安装node-sass有时候有问题。

**Comment by fhvknb** [comment]
好吧，谢谢
