### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by fengyinchao** [shinygang/Vue-cnodejs#84]
消息页，未读消息，当未读消息数为1时，页面背景的loading效果还在。。。

**Comment by WM520** [comment]
<img width="553" alt="2f9cab31-6082-431f-b65c-733ffc26f8f4" src="https://cloud.githubusercontent.com/assets/16432354/24897686/7804c40e-1ecc-11e7-9a3f-2504b9785151.png">

为什么启动就报错

**Comment by shinygang** [comment]
谢谢提醒，已处理
