### ISSUE TITLE
运行时报错，请问应该怎么解决这个问题

### ISSUE THREAD

**Issue by wuxinlai** [shinygang/Vue-cnodejs#88]
在执行npm install 时报：
npm WARN deprecated autoprefixer-loader@3.2.0: Please use postcss-loader instead of autoprefixer-loader
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
然后执行npm run dev 是：
ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ multi app
ERROR in Cannot find module 'babel-runtime/helpers/interop-require'
 @ multi app
项目用的node 6.10.0  npm 4.4.1
知道怎么什么问题的谢谢指导啦

**Comment by shinygang** [comment]
@wuxinlai 你模块没安装好，重新安装模块吧。

**Comment by wuxinlai** [comment]
在安装的时候node-sass报错，下载不了.node文件，在网上找了个解决方案是手动下载然后安装，但是这样的方法不是很好，请问有更好的解决方案么（是因为node版本的问题么？）

**Comment by shinygang** [comment]
@wuxinlai 安装node-sass需要翻墙。并用npm装

**Comment by wuxinlai** [comment]
@shinygang 嗯呢谢谢你了
