### ISSUE TITLE
v1.1.0 需求收集

### ISSUE THREAD

**Issue by Yunkou** [shinygang/Vue-cnodejs#9]
`v1.1.0` 开始收集需求，跟回复即可，收集差不多关闭issues，发个版本。

**Comment by oero** [comment]
为何loading那么慢.........pc web端 Chrome 
无论是clone下来的项目(自己测试),还是作者给出的在线地址,loading很久才加载完
非网速问题.求答ths

**Comment by shinygang** [comment]
@oero 首次加载我给了一个默认图，所以有几秒等待。其他页面不存在慢的情况。

**Comment by oero** [comment]
@shinygang  额,前几次加载都比较慢,后来就好了.

**Comment by shinygang** [comment]
@oero 可能和当时接口返回的速度有关系吧。

**Comment by LeslieYQ** [comment]
我来说吧， 首先应该加一个 二维码的扫描识别功能，而不是传图片之类的拉。

扫一扫就能登录。

**Comment by shinygang** [comment]
@LeslieYQ 这个我研究过，h5这方面没得好的方案，求help!

**Comment by LeslieYQ** [comment]
@shinygang 我搞定了，问题是现在限制了域名这些，如果不是安全域名，不准你调video的方式。妈蛋。。

**Comment by Yunkou** [comment]
@LeslieYQ  安全域名好搞吧，求解决方案

**Comment by LeslieYQ** [comment]
我觉得新版本应该你先列出个大计划。才好补充

**Comment by shinygang** [comment]
我目前也没想好下个版本需要做些什么，求推荐。 @Yunkou  @LeslieYQ  @mage3k  @oero

**Comment by oero** [comment]
收藏?历史浏览?我也不知道

**Comment by Yunkou** [comment]
1. [ ] 用户体验，完善UI，代码可读性
2. [ ] ES2015 重构项目
3. [ ] 组件化的最优实践

**Comment by tthallos** [comment]
我觉得 @Yunkou 说的很不错，不用先着急加功能。

**Comment by LeslieYQ** [comment]
上面有一部分我已经做了一点了 例如 es215。

**Comment by AnnatarHe** [comment]
希望能写上测试。

**Comment by sblig** [comment]
1. 左右开版，左侧目录，右侧详情 ，鼠标滚动各自侧
2. url上的#能处理掉吗？

**Comment by jon1301** [comment]
反馈一个小问题：评论中的@xxx 是从json中直接读取渲染的，但是如果去点击会破坏路径；（图片可能上传失败）

其他的就不说了，就是自己的一些小改动了。

**Comment by BuptStEve** [comment]
话说可以用 [trello](https://trello.com) 或者 [wekan](https://wekan.io) 搞个 roadmap ～=￣ω￣=～

**Comment by shinygang** [comment]
@BuptStEve 没搞懂你说这个，一起参与进来搞呗。

**Comment by shinygang** [comment]
@sblig #号需要单独服务器nginx配置，目前没法去。

**Comment by BuptStEve** [comment]
举个栗子 https://wekan.io/b/MeSsFJaSqeuo9M6bs/wekan-roadmap
