### ISSUE TITLE
修改后报语法错误

### ISSUE THREAD

**Issue by wuxinlai** [shinygang/Vue-cnodejs#90]
在尝试修改代码过后，运行的时候为什么会报语法错误，之前使用过没有问题的！！请问这个应该怎么解决？？？
ERROR in ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/home/home.vue
Module build failed: SyntaxError: E:/test/half-dev/src/views/home/home.vue: Unexpected token (108:8)

  106 |     },
  107 |     computed: {
> 108 |         ...mapGetters({
      |         ^
  109 |             showInfo: 'getShowInfo',
  110 |             userInfo: 'getUserInfo'
  111 |         }),

 @ ./src/views/home/home.vue 3:2-123
 @ ./src/routers.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by shinygang** [comment]
你模块可能出问题了，重新安装下吧。
