### ISSUE TITLE
这是什么错误 看不懂

### ISSUE THREAD

**Issue by kingrome2017** [shinygang/Vue-cnodejs#94]
![_15217097406916](https://user-images.githubusercontent.com/26545998/37761170-e340006c-2df3-11e8-884f-85f7ebbccd62.png)
![_1521709776842](https://user-images.githubusercontent.com/26545998/37761186-ec480ad8-2df3-11e8-96b8-86dca2c4eaa5.png)

**Comment by shinygang** [comment]
@kingrome2017 你怎么起的服务？

**Comment by kingrome2017** [comment]
npm run dev  用的官网最新的vue-cli 模板

**Comment by shinygang** [comment]
你list.vue里面utils.js路径是不是没对？

**Comment by kingrome2017** [comment]
方便加个 扣扣吗？

**Comment by kingrome2017** [comment]
路径没有问题

**Comment by shinygang** [comment]
429517385
