### ISSUE TITLE
不继续更新了吗

### ISSUE THREAD

**Issue by awong1900** [shinygang/Vue-cnodejs#97]

**Comment by shinygang** [comment]
@awong1900 计划等vue3.0出来后重构一版，目前暂不打算重构。

**Comment by awong1900** [comment]
恩 好 。 我有社区版本搭了一个教练社区，bbs.zuqiuxunlian.com, 想着用你的作为手机端访问，应该没什么问题吧。

**Comment by shinygang** [comment]
@awong1900 用吧。没问题。

**Comment by awong1900** [comment]
有些问题。发现没有全局设置，比如API Hostname，tab的定义等等， 这样移植起来还是不方便，也怕漏掉什么。
